# Generated by Django 4.2.4 on 2023-09-12 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('threeapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='uid',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
